version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Preparing static production deployment"
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: 'dist'
  files:
    - '**/*'
    - 'public/**/*'
  discard-paths: no